/**
 * Science In A Snapshot - Image Organization Tool
 *
 * This script moves images to their category folders based on the
 * categorization-results.json file generated by categorize-images.js
 *
 * Usage:
 *   node organize-images.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import config from './config.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function organizeImages() {
  console.log('📁 Science In A Snapshot - Image Organization');
  console.log('==============================================\n');

  const resultsPath = path.join(__dirname, 'categorization-results.json');

  // Check if results file exists
  if (!fs.existsSync(resultsPath)) {
    console.error('❌ Error: categorization-results.json not found.');
    console.error('   Please run categorize-images.js first.\n');
    process.exit(1);
  }

  // Load categorization results
  const results = JSON.parse(fs.readFileSync(resultsPath, 'utf-8'));
  console.log(`📊 Found ${results.length} images to organize\n`);

  const imagesDir = path.join(__dirname, config.IMAGES_DIR);
  let movedCount = 0;
  let skippedCount = 0;
  let errorCount = 0;

  results.forEach((item, index) => {
    const { filename, category } = item;
    const sourcePath = path.join(imagesDir, filename);
    const targetDir = path.join(imagesDir, category);
    const targetPath = path.join(targetDir, filename);

    console.log(`[${index + 1}/${results.length}] ${filename} → ${category}/`);

    // Check if source file exists
    if (!fs.existsSync(sourcePath)) {
      console.log(`   ⚠️  Source file not found, skipping...\n`);
      skippedCount++;
      return;
    }

    // Check if already in the correct location
    if (fs.existsSync(targetPath)) {
      console.log(`   ℹ️  Already in correct location\n`);
      skippedCount++;
      return;
    }

    try {
      // Ensure target directory exists
      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }

      // Move the file
      fs.renameSync(sourcePath, targetPath);
      console.log(`   ✅ Moved successfully\n`);
      movedCount++;

    } catch (error) {
      console.log(`   ❌ Error: ${error.message}\n`);
      errorCount++;
    }
  });

  // Create gallery metadata file
  console.log('📄 Creating gallery metadata file...');
  const metadata = {
    lastUpdated: new Date().toISOString(),
    totalImages: results.length,
    images: results.map((item, index) => ({
      id: index + 1,
      filename: item.filename,
      category: item.category,
      imagePath: `images/${item.category}/${item.filename}`,
      contentFile: `content/${item.category}/${path.parse(item.filename).name}.json`,
      title: path.parse(item.filename).name.replace(/[-_]/g, ' ').replace(/\b\w/g, l => l.toUpperCase()),
      hasContent: false
    }))
  };

  const metadataPath = path.join(__dirname, '..', 'gallery-metadata.json');
  fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2));
  console.log(`   ✅ Saved to gallery-metadata.json\n`);

  // Summary
  console.log('📊 Summary:');
  console.log(`   ✅ Moved: ${movedCount}`);
  console.log(`   ⏭️  Skipped: ${skippedCount}`);
  console.log(`   ❌ Errors: ${errorCount}`);
  console.log(`   📁 Total: ${results.length}\n`);

  console.log('✨ Images are now organized! Next steps:');
  console.log('   1. Run generate-content.js to create educational content');
  console.log('   2. Or manually create content JSON files in /content/ folders\n');
}

// Run the script
try {
  organizeImages();
} catch (error) {
  console.error('Fatal error:', error);
  process.exit(1);
}
